// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var todoComponent = ReasonReact.reducerComponent("TodoComponent");

function make() {
  var newrecord = todoComponent.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", undefined, React.createElement("input", {
                      id: "checkBox",
                      type: "checkbox",
                      onClick: (function () {
                          return Curry._1(self[/* send */4], /* Click */0);
                        })
                    }), "Lire reason-react !");
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* isChecked : false */0];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action !== 0) {
        console.log(action);
        console.log(state);
        return /* Update */Block.__(0, [/* record */[/* isChecked : false */0]]);
      } else {
        console.log(action);
        console.log(state);
        return /* Update */Block.__(0, [/* record */[/* isChecked */1 - state[/* isChecked */0]]]);
      }
    });
  return newrecord;
}

exports.todoComponent = todoComponent;
exports.make = make;
/* todoComponent Not a pure module */
